@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Feb 17 17:38:14 -0500 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Lab_1_tb_behav -key {Behavioral:sim_1:Functional:Lab_1_tb} -tclbatch Lab_1_tb.tcl -view C:/Users/akomm/Desktop/School/ECE 448/Labs/Lab 1/ECE448_Lab_1/Lab_1_psm_2_behav.wcfg -log simulate.log"
call xsim  Lab_1_tb_behav -key {Behavioral:sim_1:Functional:Lab_1_tb} -tclbatch Lab_1_tb.tcl -view C:/Users/akomm/Desktop/School/ECE 448/Labs/Lab 1/ECE448_Lab_1/Lab_1_psm_2_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
